# Generated by Django 4.2.3 on 2023-07-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
