# Generated by Django 4.2.3 on 2023-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
